# Student Practice Tasks

In [17]:
import sqlite3                        
import pandas as pd                  
conn = sqlite3.connect('my_data.db')

1. SELECT: *Sales Data*

In [10]:
# TASK: Display sale_date, product, and price from the sales table.

# Read sales.csv into the sales table
pd.read_csv("sales.csv").to_sql('sales', conn, if_exists='replace', index=False)

# Select the three columns
pd.read_sql_query('''
SELECT sale_date, product, price FROM sales
''', conn)

    sale_date     product   price
0    9/1/2026      Laptop  999.99
1    9/1/2026       Mouse   24.99
2    9/2/2026     Monitor  199.99
3    9/2/2026    Keyboard   49.99
4    9/3/2026      Laptop  999.99
5    9/3/2026  Headphones   79.99
6    9/4/2026       Mouse   24.99
7    9/4/2026     Monitor  199.99
8    9/5/2026      Laptop  999.99
9    9/5/2026    Keyboard   49.99
10   9/6/2026  Headphones   79.99
11   9/6/2026      Tablet  449.99
12   9/7/2026       Mouse   24.99
13   9/7/2026      Tablet  449.99
14   9/8/2026     Monitor  199.99
15   9/8/2026      Laptop  999.99
16   9/9/2026    Keyboard   49.99
17   9/9/2026  Headphones   79.99
18  9/10/2026      Tablet  449.99
19  9/10/2026       Mouse   24.99

2. WHERE: *Human Resources*

In [12]:
# TASK: Find employees in Chicago with more than 10 years of experience using WHERE and AND.

# Read hr_employees.csv into the 'employees' table
pd.read_csv('hr_employees.csv').to_sql('employees', conn, if_exists='replace', index=False)
pd.read_sql_query('''
SELECT name, department, city, years_experience
FROM employees
WHERE years_experience > 10 AND city = 'Chicago'
''', conn)

   name  department     city  years_experience
0  Lily  Operations  Chicago                17

3. ORDER BY: *Real Estate*

In [18]:
# TASK: Display the three largest properties by square footage using ORDER BY and LIMIT.

# Read realestate_listings.csv into 'listings' table
pd.read_csv('realestate_listings.csv').to_sql('listings', conn, if_exists='replace', index=False)
pd.read_sql_query('''
SELECT *
FROM listings
ORDER BY sqft DESC
LIMIT 3
''', conn)

,listing_id,neighborhood,property_type,bedrooms,sqft,list_price,days_on_market
0,204,Riverside,Condo,5,3736,979000,71
1,206,Maple Grove,Condo,5,3693,1001000,52
2,209,Maple Grove,House,1,3499,661000,116

4. GROUP BY: *Marketing*

In [22]:
# TASK: Calculate total weekly impressions using SUM() and GROUP BY.

# Read marketing_campaigns.csv into 'campaigns' table
pd.read_csv('marketing_campaigns.csv').to_sql('campaigns', conn, if_exists='replace', index=False)
pd.read_sql_query('''
SELECT week, SUM(impressions) AS total_impressions
FROM campaigns
GROUP BY week
''', conn)

   week  total_impressions
0     1             181454
1     2              74972
2     3             193242
3     4             180795
4     5             264615
5     6             229892
6     7             235470
7     8             253354

5. HAVING: *Restaurant*

In [30]:
# TASK: Find dates when total restaurant sales exceeded $400.

# Read restaurant_orders.csv into 'orders' table
pd.read_csv('restaurant_orders.csv').to_sql('orders', conn, if_exists='replace', index=False)
pd.read_sql_query('''
SELECT order_date, SUM(order_total) AS day_sales
FROM orders
GROUP BY order_date
HAVING SUM(order_total) > 400
''', conn)

   order_date  day_sales
0  2026-10-02     492.14
1  2026-10-05     850.10
2  2026-10-07     415.94
3  2026-10-12     633.98

6. Aggregate Functions: *Healthcare*

In [32]:
# TASK: Find the average patient age and longest waiting time for each doctor.

# Read clinic_visist.csv into 'visits' table
pd.read_csv('clinic_visits.csv').to_sql('visits', conn, if_exists='replace', index=False)
pd.read_sql_query('''
SELECT doctor, COUNT(*) AS total_visits,
       ROUND(AVG(wait_minutes), 1) AS avg_wait_minutes
FROM visits
GROUP BY doctor
''', conn)

      doctor  total_visits  avg_wait_minutes
0  Dr. Adams             9              43.7
1   Dr. Chen             5              25.2
2  Dr. Gomez             6              45.8
3  Dr. Patel             8              49.0
4  Dr. Scott             7              35.1

7. JOIN: *Banking*

In [36]:
# TASK: Join customer and transaction tables to calculate total transaction amounts by branch.

# Read bank_transactions.csv and bank_customers.csv each to their own tables - 'transactions' and 'customers', respectively
pd.read_csv('bank_transactions.csv').to_sql('transactions', conn, if_exists='replace', index=False)
pd.read_csv('bank_customers.csv').to_sql('customers', conn, if_exists='replace', index=False)
pd.read_sql_query('''
SELECT c.branch, SUM(amount) AS total_transactions
FROM transactions AS t
JOIN customers AS c ON t.customer_id = c.customer_id
GROUP BY c.branch
''', conn)

      branch  total_transactions
0    Airport            15177.98
1    Main St             3581.19
2  Northgate            19546.49
3   Westside            13996.30